name: Python CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sleep for 80 seconds
        run: sleep 80

      - name: Install Python packages
        run: make py_install

      - name: Lint Python code
        run: make py_lint

      - name: Run Python tests
        run: make py_test

      - name: Format Python code
        run: make py_format

      - name: Pull latest changes
        run: git pull

      # Set up Git authentication using PAT
      - name: Set up Git authentication
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/yabeizeng1121/Mini8.git

      - name: generate_and_push
        run: make generate_and_push

      - name: Deploy
        run: make py_deploy
